name: Connect to AS400

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  connect-to-as400:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm install

      - name:   
 Connect to AS400
        run: |
          node -e "
            const ibmiCl = require('ibmi-cl');

            const connectionOptions = {
              host: 'pub400.com',
              port: 22,
              username: 'RPAREEK',
              password: 'AUGUST@19',
              library: 'your_as400_library' // Optional
            };

            ibmiCl.connect(connectionOptions, (err) => {
              if (err) {
                console.error('Error connecting to AS400:', err);
                process.exit(1);
              }
              console.log('Connected to AS400 successfully!');
            });
          "

      - name: Run AS400 commands (optional)
        run: |
          node -e "
            // ... your AS400 command logic here ...
          "
