name: Connect to AS400

on:
  push:
    branches: [main]

jobs:
  connect-to-as400:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Download and configure ibmjtopen
        run: |
          wget https://public.dhe.ibm.com/software/ibmi/tools/free/jtopen/latest/jtopen-current.jar
          echo "export CLASSPATH=\$CLASSPATH:jtopen-current.jar" >> $GITHUB_ENV
          echo "export PATH=\$PATH:\$GITHUB_WORKSPACE/jtopen-current.jar" >> $GITHUB_ENV

      - name: Connect to AS400
        run: |
          java -jar jtopen-current.jar -s <pub400.con> -u <RPAREEK> -p <AUGUST@19> -c <AS400_CONNECTION_TYPE> -l <RPAREEK>

      - name: Run AS400 commands
        run: |
          java -jar jtopen-current.jar -s <AS400_HOST> -u <AS400_USER> -p <AS400_PASSWORD> -c <AS400_CONNECTION_TYPE> -l <RPAREEK> -e "CRTDTAAARA RPAREEK/T1"

      - name: Handle connection errors
        if: ${{ steps.connect-to-as400.outputs.connection_status == 'failed' }}
        run: |
          echo "Connection to AS400 failed. Please check your credentials and connection settings."
          exit 1
