name: Setup Node.js and Deploy to IBM i

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    branches:
      - main # or your default branch

jobs:
  deploy_ibm_i:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # or your desired Node.js version
          cache: 'npm'

      - name: Install IBM i CI tools
        run: npm i -g @ibm/ibmi-ci

      - name: Deploy to IBM i
        run: |
          ici \
            --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
            --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
            --push "." \
            --cmd "/QOpenSys/pkgs/bin/gmake BIN_LIB=CMPSYS"
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }} #Use secrets for sensitive data
          IBMI_USER: ${{ secrets.IBMI_USER }} #Use secrets for sensitive data
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }} #Use secrets for sensitive data
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT || 22 }} #Use secrets, default to 22 if not set.
